# fly.toml app configuration file generated for zapier-elixir on 2025-11-12T17:12:57-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zapier-elixir'
primary_region = 'dfw'

[build]
  dockerfile = "Dockerfile"

[env]
  PHX_HOST = "zapier-elixir.fly.dev"
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  # Health checks disabled due to SSL redirect issue
  # [[http_service.checks]]
  #   grace_period = "10s"
  #   interval = "30s"
  #   method = "GET"
  #   timeout = "5s"
  #   path = "/health/live"

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 8
