# fly.toml app configuration file generated for zapier-triggers-rust on 2025-11-12T17:05:38-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zapier-triggers-rust'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'
  RUST_BACKTRACE = '1'
  RUST_LOG = 'info,zapier_triggers=debug'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '4GB'
  cpu_kind = 'shared'
  cpus = 8

[[statics]]
  guest_path = '/app/public'
  url_prefix = '/public'

[[metrics]]
  port = 9090
  path = '/metrics'
